var skills = [
  { name: "Exercise",
    tagline: "Running, Walking, etc.",
    photo: 'http://source.unsplash.com/vjmNWcs-_54'},
  { name: "Write",
    tagline: "Poetry, Stories, Journal, Blog",
    photo: 'http://source.unsplash.com/dvK_CT1Wg78'},
  { name: "Scribble",
    tagline: "Doodle on paper",
    photo: 'http://source.unsplash.com/73LVfWy-t0A'},
  { name: "Be with other people",
    tagline: "",
    photo: 'http://source.unsplash.com/Pw5uvsFcGF4'},
  { name: "Watch a favorite TV show",
    tagline: "Like The Office",
    photo: 'http://source.unsplash.com/ngMtsE5r9eI'},
  { name: "Browse Reddit",
    tagline: "",
    photo: 'http://source.unsplash.com/ne3qiwViW3A'},
  { name: "Go see a movie",
    tagline: "Yum...popcorn",
    photo: 'http://source.unsplash.com//GF8VvBgcJ4o'},
  { name: "Do a wordsearch or crossword",
    tagline: "or Words With Friends",
    photo: 'http://source.unsplash.com/8ziKncAPUpY'},
  { name: "Do schoolwork",
    tagline: "",
    photo: 'http://source.unsplash.com/tImZgkTcCbQ'
  },
  { name: "Play a musical instrument",
    tagline: "Piano, Violin, Guitar, Drums",
    photo: 'http://source.unsplash.com/KoQxb6taoLA'},
  { name: "Paint your nails, do your make-up or hair",
    tagline: "Mini-Spa Day!",
    photo: 'http://source.unsplash.com/7_Gkf5JZRv4'},
  { name: "Sing",
    tagline: "",
    photo: 'http://source.unsplash.com/PRVvL8bfcTA'},
  { name: "Study the Sky",
    tagline: "",
    photo: 'http://source.unsplash.com/ef0sXQtnCYU'},
  { name: "Cover yourself with Band-Aids where you want to cut",
    tagline: "",
    photo: 'http://source.unsplash.com/wb3s6DYj4U0'},
  { name: "Let yourself cry",
    tagline: "",
    photo: 'http://source.unsplash.com/V2sJMCDdslA'},
  { name: "Take a nap",
    tagline: "(only if you're tired)",
    photo: 'http://source.unsplash.com/wUMfrBfNNq0'},
  { name: "Take a hot shower or relaxing bath",
    tagline: "",
    photo: 'http://source.unsplash.com/yAlH5qA7qk0'},
  { name: "Play with a pet",
    tagline: "",
    photo: 'http://source.unsplash.com/mx0DEnfYxic'},
  { name: "Go Shopping",
    tagline: "",
    photo: 'http://source.unsplash.com//Fzde_6ITjkw'},
  { name: "Clean Something",
    tagline: "",
    photo: 'http://source.unsplash.com/cpIgNaazQ6w'},
  { name: "Knit or Sew",
    tagline: "",
    photo: 'http://source.unsplash.com/_qYhK19o0rA'},
  { name: "Read a good book",
    tagline: "",
    photo: 'http://source.unsplash.com/YSN4xhXuPig'},
  { name: "Listen to Music",
    tagline: "",
    photo: 'http://source.unsplash.com/PDX_a_82obo'},
  { name: "Try some aromatherapy",
    tagline: "Candle, Lotion, Room Spray",
    photo: 'http://source.unsplash.com/OjUPxJgJ4JQ'},
  { name: "Meditate",
    tagline: "",
    photo: 'http://source.unsplash.com/-Q_t4SCN8c4'},
  { name: "People watch in public",
    tagline: "",
    photo: 'http://source.unsplash.com/ohQPI-OQmcg'},
  { name: "Bake cookies",
    tagline: "",
    photo: 'http://source.unsplash.com/_Rp-slWXGpU'},
  { name: "Alphabetize your CDs/DVDs/Books",
    tagline: "",
    photo: 'http://source.unsplash.com/1J8k0qqUfYY'},
  { name: "Paint or Draw",
    tagline: "",
    photo: 'http://source.unsplash.com/nP8rZN2xNCw'},
  { name: "Rip paper into itty-bitty pieces",
    tagline: "",
    photo: 'http://source.unsplash.com/hkRtGTohgjM'},
  { name: "Shoot hoops, kick a ball",
    tagline: "",
    photo: 'http://source.unsplash.com/Lk4ELF16vs0'},
  { name: "Write a letter or send an email",
    tagline: "",
    photo: 'http://source.unsplash.com/Pf5iPTOJQ3g'},
  { name: "Plan your dream room",
    tagline: "Down to the colors and furniture",
    photo: 'http://source.unsplash.com/yxRYfsrdyWU'},
  { name: "Hug a pillow or stuffed animal",
    tagline: "",
    photo: 'http://source.unsplash.com/eqyY1dIXcPg'},
  { name: "Hyperfocus on a rock, hand, etc",
    tagline: "",
    photo: 'http://source.unsplash.com/WVIntWsM0Cw'},
  { name: "Dance",
    tagline: "",
    photo: 'http://source.unsplash.com/PhzM4ABsTiQ'},
  { name: "Make hot chocolate, milkshake or smoothie",
    tagline: "",
    photo: 'http://source.unsplash.com/rWbWQtcPFuE'},
  { name: "Play with modeling clay or Play-Dough",
    tagline: "",
    photo: 'http://source.unsplash.com/cXwoKtwRz00'},
  { name: "Go for a nice, long drive",
    tagline: "",
    photo: 'http://source.unsplash.com/hdd0StA8kic'},
  { name: "Complete something you've been putting off",
    tagline: "",
    photo: 'http://source.unsplash.com/ZMMXSRMSoI8'},
  { name: "Draw on yourself with a marker",
    tagline: "",
    photo: 'http://source.unsplash.com/Vrtt2KzOxOk'},
  { name: "Start a new hobby",
    tagline: "",
    photo: 'http://source.unsplash.com/3_ochNfpd3U'},
  { name: "Look up recipes, cook a meal",
    tagline: "",
    photo: 'http://source.unsplash.com/zQLYPVt89d4'},
  { name: "Look at pretty things",
    tagline: "like flowers or art",
    photo: 'http://source.unsplash.com/sFnAAPenaAA'},
  { name: "Create or build something",
    tagline: "",
    photo: 'http://source.unsplash.com/Alm7tmPVmSU'},
  { name: "Pray",
    tagline: "",
    photo: 'http://source.unsplash.com/ReEqHw2GyeI'},
  { name: "Make a list of blessings in your life",
    tagline: "",
    photo: 'http://source.unsplash.com/4-VgrP9SgQw'},
  { name: "Read the Bible",
    tagline: "",
    photo: 'http://source.unsplash.com/nbjsRIi4X6U'},
  { name: "Go to a friend's house",
    tagline: "",
    photo: 'http://source.unsplash.com/FUgR_MEqgJg'},
  { name: "Contact a hotline",
    tagline: "or your therapist",
    photo: 'http://source.unsplash.com/h8mXDW2XniI'},
  { name: "Talk to someone close to you",
    tagline: "",
    photo: 'http://source.unsplash.com/mG-HdjYiPtE'},
  { name: "Ride a bike",
    tagline: "",
    photo: 'http://source.unsplash.com/XGkl5yYHxyA'},
  { name: "Feed the ducks, birds, or squirrels",
    tagline: "",
    photo: 'http://source.unsplash.com/p-vf1RhLzsc'},
  { name: "Color with Crayons",
    tagline: "",
    photo: 'http://source.unsplash.com/vJritQGOFvc'},
  { name: "Memorize a poem, play, or song",
    tagline: "",
    photo: 'http://source.unsplash.com/X8sHrrH_xXg'},
  { name: "Stretch",
    tagline: "",
    photo: 'http://source.unsplash.com/JGxdIlKy3lA'},
  { name: "\"Shop\" online",
    tagline: "without buying anything",
    photo: 'http://source.unsplash.com/W1B2LpQOBxA'},
  { name: "Color-coordinate your closet",
    tagline: "",
    photo: 'http://source.unsplash.com/jXfpruvSHKk'},
  { name: "Watch Fish",
    tagline: "",
    photo: 'http://source.unsplash.com/X3dHODCUKZo'},
  { name: "Make a CD or playlist of your favorite songs",
    tagline: "",
    photo: 'http://source.unsplash.com/4p0C_OiXNiM'},
  { name: "Plan your wedding, prom, or other event",
    tagline: "",
    photo: 'http://source.unsplash.com/NObT7cuEm2k'},
  { name: "Plant some seeds",
    tagline: "",
    photo: 'http://source.unsplash.com/y6OUJR4CrBM'},
  { name: "Hunt for your perfect home or car online",
    tagline: "",
    photo: 'http://source.unsplash.com/XWj-pUBFjO4'},
  { name: "Sort through your photographs",
    tagline: "",
    photo: 'http://source.unsplash.com/yj5vVBO7NZ8'},
  { name: "Play with a balloon",
    tagline: "",
    photo: 'http://source.unsplash.com/FU5uVjZSMMw'},
  { name: "Give yourself a facial",
    tagline: "",
    photo: 'http://source.unsplash.com/87InWldRhgs'},
  { name: "Find yourself some toys and play",
    tagline: "",
    photo: 'http://source.unsplash.com/0VNVxhEnkII'},
  { name: "Start collecting something",
    tagline: "",
    photo: 'http://source.unsplash.com/0yuH4tIQIYY'},
  { name: "Play video games",
    tagline: "",
    photo: 'http://source.unsplash.com/umZ-Mxz_nps'},
  { name: "Perform a random act of kindness for someone",
    tagline: "",
    photo: 'http://source.unsplash.com/NL3cq2B33yw'},
  { name: "Text or call an old friend",
    tagline: "",
    photo: 'http://source.unsplash.com/slf3hCQNw1k'},
  { name: "Write yourself an \"I love you because...\" letter",
    tagline: "",
    photo: 'http://source.unsplash.com//u3ajSXhZM_U'},
  { name: "Write a letter to someone that you may never send",
    tagline: "",
    photo: 'http://source.unsplash.com/DR31squbFoA'},
  { name: "Smile at least five people",
    tagline: "",
    photo: 'http://source.unsplash.com/6qn1NmPMKFQ'},
  { name: "Play with little kids",
    tagline: "",
    photo: 'http://source.unsplash.com/UYDoE_AyJQs'},
  { name: "Go for a walk",
    tagline: "alone or with a friend",
    photo: 'http://source.unsplash.com/hqaDFFsCJgE'},
  { name: "Put a puzzle together",
    tagline: "",
    photo: 'http://source.unsplash.com/3y1zF4hIPCg'},
  { name: "Clean your room",
    tagline: "",
    photo: 'http://source.unsplash.com/jCPL0oxBhB0'},
  { name: "Try to do handstands, cartwheels, or backbends",
    tagline: "",
    photo: 'http://source.unsplash.com/JPGS3UGKKag'},
  { name: "Yoga",
    tagline: "",
    photo: 'http://source.unsplash.com/I2YSmEUAgDY'},
  { name: "Teach your pet a new trick",
    tagline: "",
    photo: 'http://source.unsplash.com/fkLr2QOQitk'},
  { name: "Learn a new language",
    tagline: "",
    photo: 'http://source.unsplash.com/xy4zPgetBQg'},
  { name: "Jump on a trampoline",
    tagline: "",
    photo: 'http://source.unsplash.com/Kl8-SueS_BI'},
  { name: "Hug a friend or family member",
    tagline: "",
    photo: 'http://source.unsplash.com/7-gtkXm2b5U'},
  { name: "Make a list of goals for the week/month/year/5 years",
    tagline: "",
    photo: 'http://source.unsplash.com/-1_RZL8BGBM'}
];

var background = document.querySelector(".large-hero");
var title = document.querySelector(".title");
var subtitle = document.querySelector(".subtitle");
var resetButton = document.querySelector(".reset");

resetButton.addEventListener("click", function(){
  var index = Math.floor(Math.random() * skills.length);

  background.style.backgroundImage = "url(" + skills[index].photo + ")";
  title.textContent = skills[index].name;
  subtitle.textContent = skills[index].tagline;

});
